In [2]:
import seaborn as sns
import pandas as pd

In [10]:
films_info = pd.read_csv('.\data\info.csv')
f = []
for i in range(10):
    f.append(pd.read_csv('.\data\short-comments\\{}.csv'.format(i)))

In [11]:
films_info

,id,name,scores,box-office,five,four,three,two,one
0,3042261,西线无战事 Im Westen nichts Neues,8.6,62551,44.3,42.1,11.9,1.3,0.4
1,35779959,危笑 Smile,6.3,22093,6.7,23.6,51.0,15.9,2.9
2,35730910,野蛮人 Barbarian,6.9,20812,10.1,36.7,42.3,8.6,2.3
3,35240874,共助2：国际 공조2:인터내셔날,7.1,16396,12.9,37.6,43.7,5.1,0.7
4,35441582,6/45 육사오,7.7,25701,18.5,49.3,29.7,2.2,0.3
5,35801819,珀尔 Pearl,7.3,22514,14.2,43.2,36.7,4.8,1.1
6,35426373,狼狩猎 늑대사냥,5.9,9451,7.7,15.8,46.4,23.4,6.7
7,26641055,良心护士 The Good Nurse,6.9,9030,7.9,37.5,49.4,4.7,0.6
8,36118263,地狱尖兵 Лучшие в аду,8.1,4617,40.0,36.7,17.0,3.0,3.3
9,35017155,哥们儿 Bros,7.3,7543,18.4,37.8,34.6,7.3,1.9

In [12]:
f[1]

,seen,username,id,time,location,votes,star,comment
0,1,winteriscommin,200067839,2022-09-29 00:12:08,澳大利亚,295,40,在新交的好兄弟们面前立了胆大包天的人设，结果被jump scare吓得滋哇乔叫，怪丢人的😓😓
1,1,Superbia,152072392,2022-09-30 10:41:21,美国,239,40,再次证明欧美人拍不好单纯的鬼片。本来是年度最期待的horror，毕竟是和个人比较喜欢的《它在...
2,1,毛小惺,sugertown,2022-09-27 06:14:39,英国,505,30,伪恐怖片爱好者看完后需要看10遍帕丁顿熊安抚我的魂魄
3,1,24/7,149946560,2022-09-27 12:43:56,美国,440,30,9/26/2022 学校pre-screening 从来没有看过jump scare这么密集...
4,1,🧊 ʜᴀɴɴᴀ,227060134,2022-09-29 18:47:57,澳大利亚,191,40,今天在土澳看了 剧情一般 没有交代的很清楚 jump scare不错 搭配影厅巨大音效有够吓...
...,...,...,...,...,...,...,...,...
395,0,y河,192067804,2022-10-18 09:05:26,江苏,0,豆友,NaN
396,0,猪包,166047357,2022-06-24 01:56:10,NaN,0,喜欢题材,NaN
397,0,顽固污渍,NGC6814,2022-06-23 22:56:40,NaN,0,希望别诈骗我,NaN
398,0,餃子,186231411,2022-10-14 02:15:25,宁夏,0,别让我失望,NaN
399,0,贪嗔痴,163474618,2022-06-25 17:47:00,NaN,0,预告片狠狠吸引人,NaN